name: mobile
description: "A new Flutter project."
# flutter pub run build_runner build --delete-conflicting-outputs
# dart run flutter_native_splash:create
# flutter build appbundle --flavor prod lib/main_prod.dart --release./gradlew build
# flutter run --flavor prod -t lib/main_prod.dart --release

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2

  auto_route: 5.0.4
  json_serializable: 6.7.1
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  freezed: 2.4.5
  intl: 0.18.1
  dio: 5.3.4
  flutter_bloc: 8.1.3
  flutter_localizations:
    sdk: flutter
  fluttertoast: 8.2.4
  logger: 2.2.0
  shared_preferences: 2.2.3
  text_to_speech: 0.2.3
  flutter_blue_plus: 1.32.4
  permission_handler: 11.3.1
  flutter_bluetooth_serial: 0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  build_runner: 2.4.6
  auto_route_generator: 5.0.3
  

flutter:
  uses-material-design: true

  fonts:
    - family: SVN
      fonts:
        - asset: assets/font/SVN-Merge Bold.otf